export const filterKeys = [
  "description",
  "studentFirstName",
  "grade",
  "guardianName",
  "email",
  "phone",
  "mobile",
  "city",
];
export const filterKeysValues = {
  gender: ["male", "female", "other"],
  hostel: ["true", "false"],
  state: ["Rajasthan", "Chhattisgarh"],
  enquirySource: ["website", "referral", "school fair"],
  country: [
    "China",
    "India",
    "USA",
    "Indonesia",
    "Brazil",
    "Russia",
    "Japan",
    "Mexico",
    "Nigeria",
    "Pakistan",
    "Germany",
    "Philippines",
    "Vietnam",
    "Turkey",
    "United Kingdom",
    "Egypt",
    "France",
    "Thailand",
    "Italy",
    "South Korea",
  ],
};
